### ISSUE TITLE
ChatKit only get the first message from a dialog in Firebase

### ISSUE THREAD

**Issue by Ministoud** [stfalcon-studio/ChatKit#159]
Hey everyone,
So, let me explain,
All the information for my app (like users' ID, messages in a dialog, ...) are stock in Firebase(Firestore).

So, when I open a dialog, I download all information from the database, I can't get only the information I want because of the asynchronous tasks.

In the ``Author`` and ``Message`` class I assign all the variables with those I downloaded in the database. And because I have more than one message to load, I use a ``for`` loop to get my documents one by one, with an integer that I increment to get the correct one.

It's look like this: 
```java
private void getMessage() {
        Message amessage = new Message();
        for (Object ignored : messData.values()) {
            adapter.addToStart(amessage, true);
            intNumMessage++;
        }
intNumMessage = 1;
```
And my ``Author`` & ``Message`` class like this:

```java
public class Message implements IMessage {

        String text;

        @Override
        public String getId() {
            return intNumMessage.toString();
        }

        @Override
        public String getText() {
            Map<String, Object> results = (Map<String, Object>)messData.get(intNumMessage.toString());
            text = results.get("Text").toString();
            return text;
        }

        Author author = new Author();

        @Override
        public Author getUser() {
            return author;
        }

        @Override
        public Date getCreatedAt() {
            Map<String, Object> results = (Map<String, Object>)messData.get(intNumMessage.toString());
            Date createdAt = (Date)results.get("Time");
            return createdAt;
        }
```

```java
public class Author implements IUser {

        String id;
        String name;

        @Override
        public String getId() {
            Map<String, Object> results = (Map<String, Object>) messData.get(intNumMessage.toString());
            id = results.get("Sender").toString();
            return id;
        }

        @Override
        public String getName() {
            for (DocumentSnapshot document : usersData) {
                if (document.getId() == id) {
                    name = document.getData().get("Nickname").toString();
                }
            }
            return name;
        }

        @Override
        public String getAvatar() {
            return null;
        }
    }
```
But with the ``for`` loop, the app show the correct number of message bubble, but they all have the same attributes: they all have the same text, the same date, the same sender, ...

With the debugger I could see that the app do the ``getCreatedAt`` method and continue the program, but it will get the rest of the data only when the code is finished. So, if I have 5 messages in a dialog, it will display 5x the first message (because of the ``
intNumMessage= 1;`` , if I change “1” by “2” it will display 5x the second message)

I'm stuck for hours now, has anybody an idea to get the data from Firebase and display all messages ?
Thanks a lot !

**Comment by brandon-haugen** [comment]
It looks like you have a few problems if this is all of the code you have written so far

- the `for` loop in `getMessage()` uses the same instance (`amessage`) of `Message` for every object you are iterating through without changing it any, this might be why you are seeing the same message repeated
- it looks like both the `Author` and `Message` classes are designed to pull from the `messData` object each time they need to get data, these classes could hold that data though instead of looking it up each time they need to get it

Hopefully if you look at those items it will lead you in the right direction.

**Comment by Ministoud** [comment]
Hey again, 
Sorry for my late response and thank you for your answer. 

For the first point, I figure that you mean that I have to put the ``
Message amessage
= new Message();``
inside the ``
for`` loop ? 

And for the second point I really don't know what to do, maybe you're right but the both classes get the data in the very end of program, so I can't find how to force them to get information... 

Sorry for this, I'm programming in Android for only 3 weeks now, so Java is pretty new for me.

**Comment by brandon-haugen** [comment]
> For the first point, I figure that you mean that I have to put the Message amessage = new Message();
inside the for loop ?

It would probably be better for it to be in the `for` loop and you probably want to assign `intNumMessage` to a member variable of each instance of the `Message` class that you create if you are going to keep the data outside of the `Message` instances you create.

Which leads to the second point. Instead of storing a number in each `Message` instance, you could store the data directly in each instance of the `Message` class that you create by doing something like

```java
for (Object ignored : messData.values()) {
    // create a new instance of the Message class
    Message amessage = new Message();

    // get the data for the message from messData
    Map<String, Object> results = (Map<String, Object>)messData.get(intNumMessage.toString());

    // assign the Text to the instance of Message class created earlier
    amessage.text = = results.get("Text").toString();

    // now add the instance of the Message class to the adapter
    adapter.addToStart(amessage, true);

    // then update intNumMessage for the next iteration of the loop
    intNumMessage++;
}
```

Without knowing what `messData` really is, it is hard to know if there is a better way to do this or not.

Just like in the example code above, we assign a value to the `text` member of `amessage` you can also assign the `author` as well. It looks like currently, the code is creating a blank `Author` instead of one where the information for the `Author` is filled in.

**Comment by Ministoud** [comment]
Ho god I didn't know that you can put values that easily into a class, I understand the logic now !

So I put back the classes into their initial state, wich was shown in the documentation, and change my ``getMessage`` method to correspond to what you show me... and... it finally works !

Thanks a lot, you helped and learned me something =)
Best regards !

**Comment by brandon-haugen** [comment]
Glad you got it working!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
