### ISSUE TITLE
Getting rendering problems in Android Studio when i use ...stfalcon.chatkit.messages.MessagesList in a layout

### ISSUE THREAD

**Issue by julio4949** [stfalcon-studio/ChatKit#9]
The message I am getting is:
You can't set adapter to MessagesList. Use #setAdapter(MessagesListAdapter) instead

**Comment by troy379** [comment]
Hello @julio4949 !
This behavior is normal, because both `DialogsList` and `MessagesList` is throwing an exception on `RecyclerView.setAdapter(Adapter adapter)` method. Android Studio's preview is using this method by default, so that's why you see this error.
However, even if this problem didn't exists, you would just see the default RecyclerView preview and nothin more.

Best regards, Alexander
